# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  sendgrid_username: <%= ENV['SENDGRID_USER'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  secret_key_base: 8f70b9ca2513cbb62f599b145c1d256b6372d47ee80266fd73dab1fbe2acd8826eb324398e79f30d6fe28d14cb6f1039e4c37cbf67410809d29060c3d050417f

test:
  secret_key_base: d33d2be004baa1cb5179a24d4de7fe0e8c8169117b332448f824ab6246b6a95330c8223aa8219ebb70d395f7de96ea5363a94fdde7ee1e214bf71e01740844bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_username: <%= ENV['SENDGRID_USER'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  host: <%= ENV['HOST'] %>
